#!/bin/sh

exec 2>&1

IP=192.168.1.4

echo "Looking for $IP"

if [ $(ping -c 2 $IP > /dev/null; echo $?) -eq 0 ]; then
  echo "Found $IP"
  chpst -u greggory rsync -av brooke@$IP:~/Desktop /backups/brooke/Desktop
  echo "Backup complete"
  sleep 1h
else
  echo "$IP not found"
  sleep 5m
fi
